---
version: '3.4'
services:

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L12-v2
    environment:
      ENABLE_CUDA: '0'
    ports:
      - 8080:8080
      # NVIDIA_VISIBLE_DEVICES: 'all'
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - capabilities: 
    #         - 'gpu'